Repository EntryDSM/Casper-Recruitment, pull requests merged in 2025-03, with the labels that each got.

#37 Feature/36 modify existing security and auth logic #36 Open
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/OauthReissueService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/RefreshToken.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/User.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/enums/UserRole.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/repository/RefreshTokenRepository.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/repository/UserRepository.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/presentation/dto/request/LogoutRequest.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/presentation/dto/request/RefreshTokenRequest.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/RedisConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/SecurityConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/ErrorCode.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/exception/RefreshTokenNotFoundException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/JwtTokenProvider.kt
  src/main/resources/application.yaml
Labels: refactor

#39 setting/#34 add coderabbit.yml
  .coderabbit.yaml
Labels: setup

#38 Feature/31 Google oauth development
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/enums/OauthType.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/UnsupportedProviderException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/presentation/controller/Oauth2Controller.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/presentation/dto/GithubUserInformation.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/GithubUserService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/GithubUserTokenValidationService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/GithubUserValidationService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/LogoutService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/OauthReissueService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/TokenBlackListService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/RefreshToken.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/User.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/enums/UserRole.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/repository/RefreshTokenRepository.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/repository/UserRepository.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/presentation/dto/request/LogoutRequest.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/presentation/dto/request/RefreshTokenRequest.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/service/UserService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/RedisConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/SecurityConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/ErrorCode.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/controller/GithubApiClient.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/dto/GithubOrganizationResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/dto/GithubUserResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/service/TokenAuthenticator.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/JwtConstants.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/OAuth2UserInfo.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/CustomOAuth2AuthenticationFailureHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/GithubAuthenticationFailureHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/GithubAuthenticationSuccessHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/GoogleOauthService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/GoogleOauthUserService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/AuthDetails.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/CustomOauth2UserDetails.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/GoogleUserDetails.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/auth/exception/RefreshTokenNotFoundException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/exception/InValidTokenFormat.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/exception/NoTokenInHeader.kt
  src/main/resources/application.yaml
Labels: enhancement

#41 Feature/35 GitHub oauth
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/EquusGithubAuthApplication.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/GithubAuthProperties.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/GithubProviderProperties.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/GithubRegistrationProperties.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/command/service/GenerateGithubTokenService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/AuthorizedClientNotFoundException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/EmptyAccessTokenException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/GitHubOAuthException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/InvalidAccessTokenException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/InvalidAuthorizationCodeException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/OrganizationMembershipErrorException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/exception/TokenExpirationMissingException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/presentation/controller/GithubAuthenticationController.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/presentation/response/GithubAccessTokenResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/service/ValidateGithubOrganizationService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/entity/User.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/presentation/dto/response/LoginSuccessResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/service/UserService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/ApplicationConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/FeignConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/SecurityConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/ErrorCode.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/controller/GithubApiClient.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/controller/GithubOAuthApiClient.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/dto/response/GithubOrganizationResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/dto/response/GithubUserResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/external/github/presentation/dto/response/LoginAccessTokenResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/GithubOAuth2LoginConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/GithubAuthenticationFailureHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/GithubAuthenticationSuccessHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/JwtTokenFilter.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/exception/ExpiredJwtTokenException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/exception/InvalidJwtTokenException.kt
  src/main/resources/application.yaml
Labels: enhancement

#45 Feature/44 develop buildSrc
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
Labels: enhancement

#43 Feature/42 development of admin user verification and google oauth email verification logic
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/command/dto/response/GithubAccessTokenResponse.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/command/service/LogoutService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/command/service/OauthReissueService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/command/service/ValidateGithubOrganizationService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/command/service/component/TokenBlackListService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/presentation/controller/GithubAuthenticationController.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/auth/presentation/controller/Oauth2Controller.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/notice/presentation/NoticeController.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/report/presentation/ReportController.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/user/service/UserService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/OAuth2LoginConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/SecurityConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/ErrorCode.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/exception/EmailDomainNotAllowedException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/exception/NotFoundOauthProvider.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/GoogleOauthService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/component/EmailDomainValidator.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/component/GoogleOauthUserService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/component/OauthRoleProvider.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/annotation/OnlyAdmin.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/annotation/OnlyUser.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/JwtTokenFilter.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/security/jwt/exception/InvalidJwtTokenException.kt
  src/main/resources/application.yaml
Labels: enhancement

#53 Feature/52 fix security + oAuth setting
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/domain/report/presentation/ReportController.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/config/SecurityConfig.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/CustomErrorController.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/CustomOauth2AuthenticationException.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/ErrorCode.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/exception/GlobalExceptionFilter.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/exception/AuthenticationPrincipalMismatch.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/CustomOAuth2AuthenticationFailureHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/GoogleOauthService.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/component/EmailDomainValidator.kt
  src/main/kotlin/entry/dsm/gitauth/equusgithubauth/global/oauth/service/component/OauthTokenService.kt
  src/main/resources/application.yaml
Labels: refactor
